name: Deploy Mule App to CloudHub 2.0

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment: dev / qa / prod"
        required: true
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build Mule Application
        run: mvn clean package -DmuleDeploy

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Deploy to CloudHub 2.0
        run: |
          mvn deploy -DmuleDeploy \
            -Duser=${{ secrets.ANYPOINT_USERNAME }} \
            -Dpass=${{ secrets.ANYPOINT_PASSWORD }} \
            -Denv=${{ github.event.inputs.environment }} \
            -DappName=${{ secrets.APP_NAME }}

      - name: Debug Info
        run: |
          echo "Deploying to environment: ${{ github.event.inputs.environment }}"
