name: Manual Rollback to UAT

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'GitHub Run ID of successful UAT deployment'
        required: true
      confirm_rollback:
        description: 'Type "yes" to confirm rollback'
        required: true
        default: 'no'

jobs:
  rollback-uat:
    if: ${{ github.event.inputs.confirm_rollback == 'yes' }}
    runs-on: ubuntu-latest
    environment: uat

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List available artifacts
        run: |
          echo "Listing artifacts for run ID: ${{ github.event.inputs.run_id }}"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.inputs.run_id }}/artifacts"

      - name: Download rollback artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.run_id }}  # Ensure this matches the artifact name
          path: rollback-uat/

      - name: Verify downloaded files
        run: |
          ls -la rollback-uat/
          cat rollback-uat/version.txt
          cat rollback-uat/run_id.txt

      - name: Prepare target directory
        run: |
          mkdir -p target
          cp rollback-uat/*.jar target/

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(cat rollback-uat/version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Rollback version: $VERSION"

      - name: Redeploy to UAT
        run: |
          mvn deploy --settings .settings/org.eclipse.core.resources.prefs -DskipMunitTests -DmuleDeploy \
            -Danypoint.username="${{ secrets.USER }}" \
            -Danypoint.password="${{ secrets.PASS }}" \
            -Danypoint.businessGroup="${{ secrets.ANYPOINT_ORG_ID }}" \
            -Denv="${{ secrets.ENV }}" \
            -Dappname="${{ secrets.APP_NAME }}" \
            -Dversion="${{ steps.extract_version.outputs.version }}" \
            -Danypoint.platform.client_id="${{ secrets.ENV_CLIENT_ID }}" \
            -Danypoint.platform.client_secret="${{ secrets.ENV_CLIENT_SECRET }}"
