name: Manual Rollback to UAT

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'GitHub Run ID of successful UAT deployment'
        required: true
      confirm_rollback:
        description: 'Type "yes" to confirm rollback'
        required: true
        default: 'no'

jobs:
  rollback-uat:
    if: ${{ github.event.inputs.confirm_rollback == 'yes' }}
    runs-on: ubuntu-latest
    environment: uat

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download rollback artifact from specific run
        uses: actions/download-artifact@v4
        with:
          name: rollback-uat-${{ github.event.inputs.run_id }}
          path: rollback-uat/

      - name: Extract version from info file
        id: extract_version
        run: |
          VERSION=$(cat rollback-uat/*/info.txt | cut -d'=' -f2)
          echo "Rollback version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Redeploy rollback JAR to UAT
        run: |
          JAR_FILE=$(find rollback-uat -name "*.jar" | head -n 1)
          cp "$JAR_FILE" target/
          mvn deploy --settings .settings/org.eclipse.core.resources.prefs -DskipMunitTests -DmuleDeploy \
            -Danypoint.username="${{ secrets.USER }}" \
            -Danypoint.password="${{ secrets.PASS }}" \
            -Danypoint.businessGroup="${{ secrets.ANYPOINT_ORG_ID }}" \
            -Denv="${{ secrets.ENV }}" \
            -Dappname="${{ secrets.APP_NAME }}" \
            -Dversion="${{ steps.extract_version.outputs.version }}" \
            -Danypoint.platform.client_id="${{ secrets.ENV_CLIENT_ID }}" \
            -Danypoint.platform.client_secret="${{ secrets.ENV_CLIENT_SECRET }}"
