name: Manual Rollback to UAT

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to rollback to (check deployment-history artifact)'
        required: true
      confirm:
        description: 'Type "confirm" to execute rollback'
        required: true

jobs:
  rollback-uat:
    if: github.event.inputs.confirm == 'confirm'
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download deployment history
        uses: actions/download-artifact@v4
        with:
          name: deployment-history
          path: .

      - name: Validate version
        id: validate_version
        run: |
          if ! grep -q "${{ github.event.inputs.version }}" deployment-history.csv; then
            echo "::error::Invalid version! Available versions:"
            cat deployment-history.csv
            exit 1
          fi
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT

      - name: Download rollback artifact
        uses: actions/download-artifact@v4
        with:
          name: rollback-${{ steps.validate_version.outputs.version }}
          path: target/

      - name: Deploy rollback version
        run: |
          mvn deploy --settings .settings/org.eclipse.core.resources.prefs \
            -DskipMunitTests -DmuleDeploy \
            -Danypoint.username="${{ secrets.USER }}" \
            -Danypoint.password="${{ secrets.PASS }}" \
            -Danypoint.businessGroup="${{ secrets.ANYPOINT_ORG_ID }}" \
            -Denv="${{ secrets.ENV }}" \
            -Dappname="${{ secrets.APP_NAME }}" \
            -Dversion="${{ steps.validate_version.outputs.version }}" \
            -Danypoint.platform.client_id="${{ secrets.ENV_CLIENT_ID }}" \
            -Danypoint.platform.client_secret="${{ secrets.ENV_CLIENT_SECRET }}"

      - name: Update deployment history
        run: |
          echo "$(date +%s),${{ steps.validate_version.outputs.version }}" >> deployment-history.csv
          echo "Rollback to ${{ steps.validate_version.outputs.version }} successful!"

      - name: Save updated history
        uses: actions/upload-artifact@v4
        with:
          name: deployment-history
          path: deployment-history.csv
          retention-days: 90
