name: Manual Rollback to UAT

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Rollback version (e.g., 1.2.3)'
        required: true
      confirm_rollback:
        description: 'Type "yes" to confirm rollback'
        required: true
        default: 'no'

jobs:
  rollback-uat:
    if: ${{ github.event.inputs.confirm_rollback == 'yes' }}
    runs-on: ubuntu-latest
    environment: uat

    steps:
      - name: Checkout rollback-artifacts branch
        uses: actions/checkout@v4
        with:
          ref: rollback-artifacts

      - name: Copy rollback JAR to target directory
        run: |
          VERSION="${{ github.event.inputs.version }}"
          mkdir -p target/
          cp rollback-jars/$VERSION/*.jar target/

      - name: Redeploy rollback JAR to UAT
        run: |
          VERSION="${{ github.event.inputs.version }}"
          mvn deploy --settings .settings/org.eclipse.core.resources.prefs -DskipMunitTests -DmuleDeploy \
            -Danypoint.username="${{ secrets.USER }}" \
            -Danypoint.password="${{ secrets.PASS }}" \
            -Danypoint.businessGroup="${{ secrets.ANYPOINT_ORG_ID }}" \
            -Denv="${{ secrets.ENV }}" \
            -Dappname="${{ secrets.APP_NAME }}" \
            -Dversion="$VERSION" \
            -Danypoint.platform.client_id="${{ secrets.ENV_CLIENT_ID }}" \
            -Danypoint.platform.client_secret="${{ secrets.ENV_CLIENT_SECRET }}"
